"""
ErrorPatternStore — persistent verbal critique memory for Phase 5B ReflexionMemory.

Stores failure critiques generated by SelfCorrectionEngine.generate_critique() as
an append-only JSONL file at .awos/error_patterns.jsonl.

Retrieved by (file_path, error_type) and injected into Worker retry prompts via
task["past_critiques"], preventing the same mistake from repeating across sessions.

Reference: Reflexion (NeurIPS 2023, arXiv:2303.11366) — verbal critique in episodic
memory improves HumanEval pass@1 from 80% to 91% without weight updates.
"""

import json
import logging
import os
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import List, Optional

logger = logging.getLogger(__name__)

_DEFAULT_STORE_PATH = ".awos/error_patterns.jsonl"
_MAX_ERROR_MSG_CHARS = 300
_MAX_CRITIQUE_CHARS  = 400


@dataclass
class ErrorPattern:
    """A single persisted failure critique."""
    __test__ = False  # suppress pytest collection warning

    task_id:    str   # task["task_id"]
    file_path:  str   # relative path, e.g. "api/users.py"
    error_type: str   # ErrorClass.name, e.g. "SYNTAX_ERROR"
    error_msg:  str   # raw error string, truncated to _MAX_ERROR_MSG_CHARS
    critique:   str   # LLM-generated verbal critique, 1-3 sentences
    timestamp:  str   # ISO 8601 UTC, e.g. "2026-05-19T08:31:00Z"

    @classmethod
    def now_timestamp(cls) -> str:
        return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    def __repr__(self) -> str:
        return f"ErrorPattern(file={self.file_path}, type={self.error_type}, ts={self.timestamp})"


class ErrorPatternStore:
    """
    Append-only JSONL store for verbal failure critiques.

    Thread-safe via atomic line append (POSIX O_APPEND is atomic for small writes).
    One record per line — crash-safe, human-readable, no dependencies.
    """

    def __init__(self, store_path: str = _DEFAULT_STORE_PATH):
        self._path = Path(store_path)
        self._path.parent.mkdir(parents=True, exist_ok=True)

    # ── Public API ────────────────────────────────────────────────────────────

    def save(self, pattern: ErrorPattern) -> None:
        """Append a new ErrorPattern to the JSONL store. Never raises."""
        try:
            with open(self._path, "a", encoding="utf-8") as f:
                f.write(json.dumps(asdict(pattern)) + "\n")
                f.flush()
        except Exception:
            logger.exception("Failed to save error pattern")
            record = asdict(pattern)
            line = json.dumps(record, ensure_ascii=False) + "\n"
            with open(self._path, "a", encoding="utf-8") as fh:
                fh.write(line)
            logger.debug(
                "[ErrorPatternStore] saved: file=%s type=%s",
                pattern.file_path, pattern.error_type,
            )
        except Exception as exc:
            logger.warning("[ErrorPatternStore] save failed: %s", exc)

    def retrieve(
        self,
        file_path: str,
        error_type: str,
        top_n: int = 3,
    ) -> List[ErrorPattern]:
        """
        Return top_n most recent ErrorPatterns matching file_path + error_type.
        Returns [] if store is empty or no match found.
        """
        if not self._path.exists():
            return []
        matches: List[ErrorPattern] = []
        try:
            with open(self._path, "r", encoding="utf-8") as fh:
                for line in fh:
                    line = line.strip()
                    if not line:
                        continue
                    try:
                        rec = json.loads(line)
                        if (
                            rec.get("file_path") == file_path
                            and rec.get("error_type") == error_type
                        ):
                            matches.append(ErrorPattern(**rec))
                    except (json.JSONDecodeError, TypeError):
                        continue
        except Exception as exc:
            logger.warning("[ErrorPatternStore] retrieve failed: %s", exc)
            return []
        # Sort by timestamp descending (most recent first), return top_n
        matches.sort(key=lambda p: p.timestamp, reverse=True)
        return matches[:top_n]

    def retrieve_all(
        self,
        file_path: str,
        error_type: str,
        limit: int = 5,
    ) -> List[ErrorPattern]:
        """Retrieve error patterns matching BOTH file_path AND error_type. Returns empty list on error."""
        try:
            if not self._path.exists():
                return []
            results: List[ErrorPattern] = []
            with open(self._path, "r") as f:
                for line in f:
                    line = line.strip()
                    if not line:
                        continue
                    try:
                        data = json.loads(line)
                    except json.JSONDecodeError:
                        continue
                    if data.get("file_path") == file_path and data.get("error_type") == error_type:
                        results.append(ErrorPattern(**data))
                        if len(results) >= limit:
                            break
            return results
        except Exception:
            logger.exception("ErrorPatternStore.retrieve_all failed")
            return []

    def retrieve_any(
        self,
        file_path: str,
        top_n: int = 3,
    ) -> List[ErrorPattern]:
        """
        Return top_n most recent ErrorPatterns matching file_path (any error_type).
        Useful when error_type is unknown at retrieval time.
        """
        if not self._path.exists():
            return []
        matches: List[ErrorPattern] = []
        try:
            with open(self._path, "r", encoding="utf-8") as fh:
                for line in fh:
                    line = line.strip()
                    if not line:
                        continue
                    try:
                        rec = json.loads(line)
                        if rec.get("file_path") == file_path:
                            matches.append(ErrorPattern(**rec))
                    except (json.JSONDecodeError, TypeError):
                        continue
        except Exception as exc:
            logger.warning("[ErrorPatternStore] retrieve_any failed: %s", exc)
            return []
        matches.sort(key=lambda p: p.timestamp, reverse=True)
        return matches[:top_n]

    def list_all(self, limit: int = 200) -> List[ErrorPattern]:
        """Return up to `limit` most recent ErrorPatterns across all files/types."""
        if not self._path.exists():
            return []
        records: List[ErrorPattern] = []
        try:
            lines = self._path.read_text(encoding="utf-8").splitlines()
            for line in lines[-limit:]:
                line = line.strip()
                if not line:
                    continue
                try:
                    records.append(ErrorPattern(**json.loads(line)))
                except (json.JSONDecodeError, TypeError):
                    continue
        except Exception as exc:
            logger.warning("[ErrorPatternStore] list_all failed: %s", exc)
        return records

    def summary(self) -> dict:
        """Return {total, by_type, by_file} counts. Returns empty dict on error."""
        if not self._path.exists():
            return {"total": 0, "by_type": {}, "by_file": {}}
        total = 0
        by_type: dict = {}
        by_file: dict = {}
        try:
            with open(self._path, "r", encoding="utf-8") as fh:
                for line in fh:
                    line = line.strip()
                    if not line:
                        continue
                    try:
                        rec = json.loads(line)
                        total += 1
                        et = rec.get("error_type", "UNKNOWN")
                        fp = rec.get("file_path", "unknown")
                        by_type[et] = by_type.get(et, 0) + 1
                        by_file[fp] = by_file.get(fp, 0) + 1
                    except (json.JSONDecodeError, TypeError):
                        continue
        except Exception as exc:
            logger.warning("[ErrorPatternStore] summary failed: %s", exc)
        return {"total": total, "by_type": by_type, "by_file": by_file}


# ── Helper: build an ErrorPattern safely truncating long strings ───────────

def make_error_pattern(
    task_id:    str,
    file_path:  str,
    error_type: str,
    error_msg:  str,
    critique:   str,
    timestamp:  Optional[str] = None,
) -> ErrorPattern:
    """Factory with truncation guards. Use this instead of constructing directly."""
    return ErrorPattern(
        task_id    = str(task_id),
        file_path  = file_path or "unknown",
        error_type = error_type or "UNKNOWN",
        error_msg  = (error_msg or "")[:_MAX_ERROR_MSG_CHARS],
        critique   = (critique or "")[:_MAX_CRITIQUE_CHARS],
        timestamp  = timestamp or ErrorPattern.now_timestamp(),
    )
