"""IntegrationReviewer: Post-execution coherence check by a strong model.

After the Planner-Worker-Verifier pipeline completes all tasks, the
IntegrationReviewer reads the total diff and asks a T4 model (Sonnet)
to validate cross-task coherence, interface consistency, and missing
edge cases.

This implements the "Integration Model" step from the Correct AI
Development Hierarchy: cheap models execute isolated tasks; a strong
model reviews/merges/refactors the integrated result.
"""

import os
import subprocess
from typing import Any

from anthropic import Anthropic


class IntegrationReviewer:
    """Reviews total diff for coherence using Claude Sonnet (T4)."""

    def __init__(self, api_key: str | None = None) -> None:
        self.api_key = api_key or os.getenv("ANTHROPIC_API_KEY")
        self.client = Anthropic(api_key=self.api_key) if self.api_key else None
        self.model = "claude-sonnet-4-6"

    # ── Public API ─────────────────────────────────────────────────────────

    def review(self, codebase_root: str, execution_log: list[dict]) -> dict[str, Any]:
        """Review the total diff after task execution.

        Returns:
            {
                "passed": bool,
                "issues": [str],
                "suggestions": [str],
                "raw_response": str,
            }
        """
        diff = self._get_diff(codebase_root)
        if not diff or not self.client:
            return {"passed": True, "issues": [], "suggestions": [], "raw_response": ""}

        prompt = self._build_prompt(diff, execution_log)
        response = self._call_model(prompt)
        return self._parse_response(response)

    # ── Internal ─────────────────────────────────────────────────────────────

    def _get_diff(self, codebase_root: str) -> str:
        """Get git diff of uncommitted changes."""
        try:
            result = subprocess.run(
                ["git", "diff", "--no-color"],
                cwd=codebase_root,
                capture_output=True,
                text=True,
                timeout=10,
            )
            return result.stdout
        except (subprocess.SubprocessError, FileNotFoundError):
            return ""

    def _build_prompt(self, diff: str, execution_log: list[dict]) -> str:
        tasks_summary = "\n".join(
            f"- Task {log['task_id']}: {log['status']} — {log['reason']}"
            for log in execution_log
        )
        return f"""You are a senior staff engineer reviewing a pull request that was generated by an AI agent executing multiple isolated tasks.

Your job is to check for CROSS-TASK INTEGRATION ISSUES that cheap models miss:
1. Missing imports (a task added a function but forgot to import it)
2. Interface mismatches (task A expects X, task B provides Y)
3. Broken call chains (function renamed in one task, not updated in others)
4. Missing error handling / edge cases
5. Inconsistent patterns (mix of old and new style)
6. TODOs or stubs left unimplemented

TASKS EXECUTED:
{tasks_summary}

GIT DIFF:
```diff
{diff[:8000]}
```

If the diff is empty, say "No changes to review."

Respond in this exact format:
VERDICT: PASS | NEEDS_FIX
ISSUES:
- <issue 1>
- <issue 2>
SUGGESTIONS:
- <suggestion 1>
"""

    def _call_model(self, prompt: str) -> str:
        if not self.client:
            return "VERDICT: PASS\nISSUES:\nSUGGESTIONS:\n"
        response = self.client.messages.create(
            model=self.model,
            max_tokens=1024,
            messages=[{"role": "user", "content": prompt}],
        )
        return response.content[0].text

    def _parse_response(self, text: str) -> dict[str, Any]:
        passed = "PASS" in text and "NEEDS_FIX" not in text
        issues = []
        suggestions = []

        in_issues = False
        in_suggestions = False
        for line in text.splitlines():
            stripped = line.strip()
            if stripped.startswith("ISSUES:"):
                in_issues = True
                in_suggestions = False
                continue
            if stripped.startswith("SUGGESTIONS:"):
                in_issues = False
                in_suggestions = True
                continue
            if stripped.startswith("VERDICT:"):
                in_issues = False
                in_suggestions = False
                continue
            if in_issues and stripped.startswith("-"):
                issues.append(stripped[1:].strip())
            if in_suggestions and stripped.startswith("-"):
                suggestions.append(stripped[1:].strip())

        return {
            "passed": passed,
            "issues": issues,
            "suggestions": suggestions,
            "raw_response": text,
        }
